spring.application.name=mundomanitas
spring.datasource.url=jdbc:mariadb://localhost:3306/mundo_manitas
spring.datasource.username=mundo_app
spring.datasource.password=ClaveSegura123!

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# mundo_app 'ClaveSegura123!'
# mundo_reportes 'ClaveReportes123!'
# mundo_desarrollador 'ClaveDev123!'
# mundo_admin 'ClaveAdmin123!'


# Rol Usuario  Contraseña 
# Estudiante alumno@mundomanitas.com 123456`
# Padre padre@mundomanitas.com 123456
# Docente docente@mundomanitas.com 123456`
# Administrador admin@mundomanitas.com 123456`